=== Adiveppa-ai/portal/BRM/xsd/config_lifecycle_states.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
================================================================================
 Copyright (c) 2007, 2012, Oracle and/or its affiliates. All rights reserved. 
This material is the confidential property of Oracle Corporation or its
licensors and may be used, reproduced, stored or transmitted only in
accordance with a valid Oracle license or sublicense agreement.
================================================================================
-->

<xs:schema
  targetNamespace="http://www.oracle.com/schemas/BusinessConfig"
  xmlns="http://www.oracle.com/schemas/BusinessConfig"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified">

  <xs:include schemaLocation="PinTypes.xsd" />

  <xs:annotation>
    <xs:documentation  xml:lang="en">
 Copyright (c) 2005, 2012, Oracle and/or its affiliates. All rights reserved. 
       This material is the confidential property of Oracle Corporation or its
       licensors and may be used, reproduced, stored or transmitted only in
       accordance with a valid Oracle license or sublicense agreement.
    </xs:documentation>
  </xs:annotation>

  <xs:element name="ObjectList">
    <xs:complexType>

       <xs:sequence>
         <xs:element name="ConfigObject" minOccurs="1" maxOccurs="unbounded">
           <xs:complexType>
             <xs:sequence>

               <xs:element name="DESCR" type="xs:string" minOccurs="0" />
               <xs:element name="NAME" type="xs:string" minOccurs="1" />

               <xs:element name="PERMITTED_SERVICE_TYPES" minOccurs="1"  maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:all>
                      <xs:element name="SERVICE_TYPE" type="PinServiceObjType" minOccurs="1" maxOccurs="1" />
                    </xs:all>
                    <xs:attribute name="elem" type="xs:int" />
                  </xs:complexType>
               </xs:element>

               <xs:element name="STATES" minOccurs="1"  maxOccurs="unbounded">
                 <xs:complexType>
                   <xs:sequence>
                     <xs:element name="INITIAL_STATE" type="xs:int" minOccurs="1" />
                     <xs:element name="SERVICE_STATE_EXPIRATION_T" type="xs:int" minOccurs="1" />
                     <xs:element name="STATE_ID" type="LifecycleState" minOccurs="1" />
                     <xs:element name="STATE_NAME" type="xs:string" minOccurs="1" />
                     <xs:element name="STRING_ID" type="xs:int" minOccurs="1" />
                     <xs:element name="STR_VERSION" type="xs:int" minOccurs="1" />

                     <xs:element name="RULES" minOccurs="0" maxOccurs="unbounded">
                       <xs:complexType>
                         <xs:sequence >
                           <xs:element name="MODULE" type="xs:string"  minOccurs="1"  maxOccurs="1" />
                           <xs:element name="NAME" type="xs:string"  minOccurs="1"  maxOccurs="1" />
                           <xs:element name="VALUE" type="xs:string"  minOccurs="1"  maxOccurs="1" />
                         </xs:sequence>
                         <xs:attribute name="elem" type="xs:int" />
                       </xs:complexType>
                     </xs:element>
                     <xs:element name="TRANSITIONS" minOccurs="0"  maxOccurs="unbounded">
                       <xs:complexType>
                         <xs:sequence>
                          <xs:element name="DEFAULT_FLAG" type="xs:int" minOccurs="1"  maxOccurs="1" />
                          <xs:element name="NEXT_STATE" type="xs:int" minOccurs="1"  maxOccurs="1" />
                          <xs:element name="POST_OPCODE" type="xs:int" minOccurs="1"  maxOccurs="1" />
                          <xs:element name="PRE_OPCODE" type="xs:int" minOccurs="1"  maxOccurs="1" />
                         </xs:sequence>
                         <xs:attribute name="elem" type="xs:int" />
                       </xs:complexType>
                     </xs:element>

                   </xs:sequence>
                   <xs:attribute name="elem" type="xs:int" />
                 </xs:complexType>
               </xs:element>

             </xs:sequence>
           </xs:complexType>
         </xs:element>

       </xs:sequence>
       <xs:attribute name="configName" type="xs:string" default="/config/lifecycle_states" />

    </xs:complexType>
  </xs:element>

</xs:schema>

=== Adiveppa-ai/portal/inventory/Templates/BRM/sys/data/config/config_lifecycle_states.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>


<!--  $Header: bus_platform_vob/slm/config/load/config_lifecycle_states.xml /cgbubrm_mainbrm.portalbase/1 2018/02/27 01:33:40 nameen Exp $ -->


<!--
 Copyright (c) 2012, 2018, Oracle and/or its affiliates. All rights reserved.

   NAME
     config_lifecycle_states.xml - Input XML file to create /config/lifecycle_states object.
   DESCRIPTION
     Input XML file to create /config/lifecycle_states object.

   NOTES
     <other useful comments, qualifications, etc.>

   MODIFIED   (MM/DD/YY)
   nameen      02/26/18 - XbranchMerge nameen_bug-27523818 from
                          cgbubrm_7.5.0.portalbase
   crunkana    01/06/12 - Creation
   crunkana    01/26/12 - Bug 13627223
   crunkana    03/08/12 - Bug 13777879

-->

<?xml-stylesheet href="__PIN_HOME__/xsd/config_lifecycle_states.xsl" type="text/xml"?>

<ObjectList
  xmlns="http://www.oracle.com/schemas/BusinessConfig"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oracle.com/schemas/BusinessConfig __PIN_HOME__/xsd/config_lifecycle_states.xsd">

   <ConfigObject>

        <DESCR>Default Lifecycle State config Object</DESCR>
        <NAME>Default Lifecycle Configuration</NAME>
        <PERMITTED_SERVICE_TYPES elem="0">
                <SERVICE_TYPE>/service/telco/gsm/telephony</SERVICE_TYPE>
        </PERMITTED_SERVICE_TYPES>
        <STATES elem="0">
                <INITIAL_STATE>1</INITIAL_STATE>
                <SERVICE_STATE_EXPIRATION_T>0</SERVICE_STATE_EXPIRATION_T>
                <STATE_ID>101</STATE_ID>
                <STATE_NAME>Preactive</STATE_NAME>
                <STRING_ID>101</STRING_ID>
                <STR_VERSION>1</STR_VERSION>
                <RULES elem="0">
                        <MODULE>AAA</MODULE>
                        <NAME>REQ_ALLOWED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="1">
                        <MODULE>AAA</MODULE>
                        <NAME>MO_ENABLED</NAME>
                       <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="2">
                        <MODULE>AAA</MODULE>
                        <NAME>MT_ENABLED</NAME>
                       <VALUE>No</VALUE>
                </RULES>
                <TRANSITIONS elem="0">
                        <DEFAULT_FLAG>1</DEFAULT_FLAG>
                        <NEXT_STATE>102</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
        </STATES>
        <STATES elem="1">
                <INITIAL_STATE>0</INITIAL_STATE>
                <SERVICE_STATE_EXPIRATION_T>90:00</SERVICE_STATE_EXPIRATION_T>
                <STATE_ID>102</STATE_ID>
                <STATE_NAME>Active</STATE_NAME>
                <STRING_ID>102</STRING_ID>
                <STR_VERSION>1</STR_VERSION>
                <RULES elem="0">
                        <MODULE>AAA</MODULE>
                        <NAME>REQ_ALLOWED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="1">
                        <MODULE>AAA</MODULE>
                        <NAME>MO_ENABLED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="2">
                        <MODULE>AAA</MODULE>
                        <NAME>MT_ENABLED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <TRANSITIONS elem="0">
                        <DEFAULT_FLAG>1</DEFAULT_FLAG>
                        <NEXT_STATE>103</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="1">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>105</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="2">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>106</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="3">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>107</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="4">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>108</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
		<TRANSITIONS elem="5">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>109</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
        </STATES>
        <STATES elem="2">
                <INITIAL_STATE>0</INITIAL_STATE>
                <SERVICE_STATE_EXPIRATION_T>30:00</SERVICE_STATE_EXPIRATION_T>
                <STATE_ID>103</STATE_ID>
                <STATE_NAME>Recharge Only</STATE_NAME>
                <STRING_ID>103</STRING_ID>
                <STR_VERSION>1</STR_VERSION>
                <RULES elem="0">
                        <MODULE>AAA</MODULE>
                        <NAME>REQ_ALLOWED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="1">
                        <MODULE>AAA</MODULE>
                        <NAME>MO_ENABLED</NAME>
                       <VALUE>No</VALUE>
                </RULES>
                <RULES elem="2">
                        <MODULE>AAA</MODULE>
                        <NAME>MT_ENABLED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="3">
                        <MODULE>AAA</MODULE>
                        <NAME>TFN_ENABLED</NAME>
                       <VALUE>No</VALUE>
                </RULES>
                <TRANSITIONS elem="0">
                        <DEFAULT_FLAG>1</DEFAULT_FLAG>
                        <NEXT_STATE>104</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="1">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>102</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="2">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>107</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="3">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>108</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
		<TRANSITIONS elem="4">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>109</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
        </STATES>
        <STATES elem="3">
                <INITIAL_STATE>0</INITIAL_STATE>
                <SERVICE_STATE_EXPIRATION_T>15:00</SERVICE_STATE_EXPIRATION_T>
                <STATE_ID>104</STATE_ID>
                <STATE_NAME>Credit Expired</STATE_NAME>
                <STRING_ID>104</STRING_ID>
                <STR_VERSION>1</STR_VERSION>
                <RULES elem="0">
                        <MODULE>AAA</MODULE>
                        <NAME>REQ_ALLOWED</NAME>
                        <VALUE>Yes</VALUE>
                </RULES>
                <RULES elem="1">
                        <MODULE>AAA</MODULE>
                        <NAME>MO_ENABLED</NAME>
                       <VALUE>No</VALUE>
                </RULES>
                <RULES elem="2">
                        <MODULE>AAA</MODULE>
                        <NAME>MT_ENABLED</NAME>
                        <VALUE>No</VALUE>
                </RULES>
                <RULES elem="3">
                        <MODULE>AAA</MODULE>
                        <NAME>TFN_ALLOWED</NAME>
                       <VALUE>Yes</VALUE>
                </RULES>
                <TRANSITIONS elem="0">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>108</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="1">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>102</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
                <TRANSITIONS elem="2">
                        <DEFAULT_FLAG>1</DEFAULT_FLAG>
                        <NEXT_STATE>107</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
		<TRANSITIONS elem="3">
                        <DEFAULT_FLAG>0</DEFAULT_FLAG>
                        <NEXT_STATE>109</NEXT_STATE>
                        <POST_OPCODE>0</POST_OPCODE>
                        <PRE_OPCODE>0</PRE_OPCODE>
                </TRANSITIONS>
        </STATES>
